### ISSUE TITLE
Clear buttons of FloatingActionsMenu

### ISSUE THREAD

**Issue by colymore** [futuresimple/android-floating-action-button#104]
Hi, i need to clear child buttons of FloatingActionsMenu, current api allow this?

**Comment by chalup** [comment]
Implemented in 2ebb00e. BTW: thanks for your pull request!

**Comment by colymore** [comment]
You are welcome :).
And now, how can i remove all childs of a FloatingActionsMenu? Actually i save a reference of a child addeds currently to ActionsMenu and when i want to remove it i do a foreach calling to remove method with the child instance, but i thinks should be other clean way. What do yo think?

**Comment by chalup** [comment]
I think that your approach *is* the clean way. Think of ListView + Adapters.
