### ISSUE TITLE
Is there a way to place labels on the right side of the button?

### ISSUE THREAD

**Issue by loeschg** [futuresimple/android-floating-action-button#109]
(original requester for labels - https://github.com/futuresimple/android-floating-action-button/issues/22)

Is there support for placing labels on the right side of a fab menu? I have an instance where I have a downward opening FAB menu on the top left side of the screen and want labels on the other side (to keep the button flush on the side of the screen). 

An example of the button placement: http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7dTZPVXhSZjkzeEU/components_lists_keylines4.png

**Comment by loeschg** [comment]
Saw this was added in https://github.com/futuresimple/android-floating-action-button/pull/76. Closing.

**Comment by loeschg** [comment]
Re-opening as I haven't seen any movement on the referenced PR (#76)

**Comment by chalup** [comment]
Implemented in 7c752e1447a9a724751a6038e26f193adf0b7122
