### ISSUE TITLE
Creating Button with TextView, Not Drawable

### ISSUE THREAD

**Issue by Dfmarulanda** [futuresimple/android-floating-action-button#110]
Im trying to create a actionbutton with a textview inside. So, it will contain a Number.
I just try to make a Drawable from a String but when i add it to the actionbutton there is not sucess.

**Comment by chalup** [comment]
I don't see why using custom drawable would not work. Share your code somewhere, maybe I'll be able to help you.

**Comment by Dfmarulanda** [comment]
Its done. My bad.
Ty
