### ISSUE TITLE
Background shadow animation

### ISSUE THREAD

**Issue by devishankar** [futuresimple/android-floating-action-button#111]
I'm using ```FloatingActionsMenu.OnFloatingActionsMenuUpdateListener()```, but the problem i'm facing is, when i use this Listener it spoils the nice flow of animation in the floating buttons, any workaround to make the animation fluid....

**Comment by chalup** [comment]
I don't quite understand what is the issue. Can you describe it in more details, or - ideally - post the code demonstrating your problem?

**Comment by mthahzan** [comment]
I think I'm experiencing the same issue as well. Below is my code to show/hide an overlay view when the FloatingActionMenu is expanded/collapsed. The expanding animation becomes laggy and it almost looks like the animation happens twice when I set this listener to the FAM. The collapsing animation doesn't seem to be broken.

FloatingActionsMenu.OnFloatingActionsMenuUpdateListener listener = new FloatingActionsMenu.OnFloatingActionsMenuUpdateListener() {
            @Override
            public void onMenuExpanded() { overlay.setVisibility(View.VISIBLE); }

            @Override
            public void onMenuCollapsed() { overlay.setVisibility(View.GONE); }
};

floatingActionsMenu.setOnFloatingActionsMenuUpdateListener(listener);

**Comment by wjwarren** [comment]
@mthahzan I had the same problem when implementing this for https://github.com/futuresimple/android-floating-action-button/issues/64. My workaround was to always have the overlay VISIBLE, remove the clickhandler and set alpha to 0 when the overlay isn't needed.

It isn't optimal, but works. :wink: 

If someone has a better solution, I would definitely like to hear it.

**Comment by mthahzan** [comment]
@wjwarren But how do you capture the collapse/expand event to change the alpha value without using the listener? Are you using an onClickListener?

**Comment by wjwarren** [comment]
I add set an `onClickListener` on the background when the menu is expanded. I remove the `onClickListener` when the menu is collapsed.

For details, have a look at my fork https://github.com/wjwarren/android-floating-action-button

**Comment by mthahzan** [comment]
I tried the `onClickListener` but since the actual size of the view is bigger than the size of the FAM, touching somewhere else (within the perimeter of the actual view) expands the FAM too. Does yours too or am I doing it wrong?

**Comment by wjwarren** [comment]
Set the `onClickListener` on the background to `null` when you collapse the FAM, that should do the trick.

**Comment by mthahzan** [comment]
Thanks mate. Will try.

**Comment by adfleshner** [comment]
@wjwarren @chalup any chance that wjwarren's fork https://github.com/wjwarren/android-floating-action-button could get pulled into this project?

**Comment by wjwarren** [comment]
@adfleshner I think my fork will need some work (meet standards, quality, feature compatibility) before it can be pulled...

Also not sure if it should be pulled. I think @chalup commented on some of the tickets that I implemented that those should not really be part of the library. In the end it is up to him. Meanwhile I try to keep my fork up to date with master.

**Comment by chalup** [comment]
Thanks for the info, will keep that in mind when I work on reference implementation of background shadow/overlay.
