### ISSUE TITLE
How to change the attribute "padding" of an FloatingActionButton?

### ISSUE THREAD

**Issue by jeansantiago** [futuresimple/android-floating-action-button#114]
When I use the fab:fab_icon attribute, the icon appears small.
I want to leave the icon fully populated in a FAB.

**Comment by chalup** [comment]
Can you post the drawables you use?

**Comment by jeansantiago** [comment]
I want this:
![image](https://cloud.githubusercontent.com/assets/3118217/5791387/032581d8-9eb2-11e4-9b2f-87522f05c97a.png)
but when I use fab:fab_icon apears:
![image](https://cloud.githubusercontent.com/assets/3118217/5791392/7d5dbbaa-9eb2-11e4-8f54-aace558a5744.png)
Is there another attribute?

**Comment by jeansantiago** [comment]
<com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_guincho"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_colorNormal="@color/blue"
            fab:fab_colorPressed="@color/blue_pressed"
            fab:fab_icon="@drawable/guincho"/>

**Comment by chalup** [comment]
What you want is not compliant with material design guidelines. I won't implement support for other size of icon drawable, but at some point I plan to add support for custom background in FABs (#58), which you'll be able to use to achieve what you want.
