### ISSUE TITLE
Titles on the right side of button

### ISSUE THREAD

**Issue by arunshankar87** [futuresimple/android-floating-action-button#120]
I am using the FAB at the bottom left corner as opposed to the traditional bottom right. But when I try to add title, the title is shown to the left of the buttons and hence pushing the menu by the width of the label. I want the menu to remain at bottom left corner and have the titles to the right of the buttons

**Comment by chalup** [comment]
Implemented in 7c752e1447a9a724751a6038e26f193adf0b7122
