### ISSUE TITLE
FABMenu button over listview

### ISSUE THREAD

**Issue by dgngulcan** [futuresimple/android-floating-action-button#122]
Hello, when fabmenu is on the list view hierarchically , listview is not scrollable from the area of fabmenu's expanded space even if menu is closed. The listview is not clickable nor scrollable inside blue area. How can we fix this?

Kind regards,

![tempfileforshare](https://cloud.githubusercontent.com/assets/1465496/5854371/bdb38faa-a235-11e4-9788-9a4075344184.jpg)

**Comment by chalup** [comment]
Nice catch, will take care of it.

**Comment by chalup** [comment]
I tried to reproduce this issue, but everything works correctly. Can you take a look at the referenced commit above and see how this differs from your use case?

**Comment by dgngulcan** [comment]
This problem were in 1.5.0, just updated to 1.8.0 and there are no problems with scrolling, however, button labels are not shown and as I checked its a known issue.
Thank you for this amazing library!
Sincerely

**Comment by chalup** [comment]
The missing labels are kindof known issue, but I can't reproduce it. So it would be great if you could contribute a code sample that shows this problem to #133.
