### ISSUE TITLE
Setting android:textViewStyle makes labels ignore fab:fab_labelStyle

### ISSUE THREAD

**Issue by wjwarren** [futuresimple/android-floating-action-button#123]
When you create a custom `textViewStyle` in a theme, apply the theme to the Activity you use the floating action button in, the properties set in `fab_labelStyle` are ignored.

**Comment by chalup** [comment]
Thanks for reporting this issue.

**Comment by chalup** [comment]
I have successfully reproduced the issue, but I have no idea how to solve it. I don't understand why using `style` attribute from XML overrides the `textViewStyle` from theme, but using ContextThemeWrapper does not. Bug? Feature?

**Comment by wjwarren** [comment]
@chalup Thanks for coming back to me. :smile: 

I don't know much about this problem, but it looks like there may be some options to explore.

1. Use `TextView.setTextAppearance(Context, int)`.
1. Using a cloned `LayoutInflater`, which is suggested on [StackOverflow](http://stackoverflow.com/a/15496425).

**Comment by chalup** [comment]
Already tried option 2, doesn't work.

**Comment by chalup** [comment]
The 1st option works, unless `textViewStyle` from theme contains style elements outside of appearance scope, like `background`.

It's still and improvement, so I'm implementing it in 0bac367. @wjwarren does that solve your use case?

**Comment by wjwarren** [comment]
@chalup Works like a charm! :)
