### ISSUE TITLE
How to put my own views inside the "FloatingActionsMenu" ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [futuresimple/android-floating-action-button#128]
I've tried doing so, but then the view itself got centered with the items, so instead of this:

...AAAAA
........BBB
............C

I got something like this:

...AAAAA
.....BBB..
.......C....

where C is the "add" button, and the others are the other views that appear above it when C is being clicked.

I think I need to change the FloatingActionsMenu code on "onLayout" , on those lines:

int addButtonLeft = r - l - mMaxButtonWidth + (mMaxButtonWidth - mAddButton.getMeasuredWidth()) / 2;

child.layout(childX, childY, childX + child.getMeasuredWidth(), childY + child.getMeasuredHeight());

What should I do? Can you please add this feature?

**Comment by chalup** [comment]
What is the use case? What are you trying to achieve?

**Comment by AndroidDeveloperLB** [comment]
I'd like to put my own views next to the FABs that appear when clicking on the add-floating-button.
If you generalize this, you could use the same method for the labels mechanism.

As an example of what I can do, I could put labels myself, and handle clicking on them as if you clicked on the new FABs.

**Comment by chalup** [comment]
I have no plans to support adding custom Views to FAM. Clickable labels will be implemented for #95.

**Comment by AndroidDeveloperLB** [comment]
@chalup Too bad. Thank you anyway.

**Comment by AndroidDeveloperLB** [comment]
Wait, the clickable labels are on the repository, or should I change the code to make it so?
Is it in merged state?

**Comment by chalup** [comment]
Not yet. I was just pointing to the already reported issue.

**Comment by AndroidDeveloperLB** [comment]
ok, thank you. I will check it out.

**Comment by AndroidDeveloperLB** [comment]
ok, i
