### ISSUE TITLE
FloatingActionsMenu change layout_alignParentRight to false

### ISSUE THREAD

**Issue by PJFonseca** [futuresimple/android-floating-action-button#129]
Hi,

How do i change the layout_alignParentRight to false in code?

I got this: 

com.getbase.floatingactionbutton.FloatingActionsMenu multiple_actions_down = (com.getbase.floatingactionbutton.FloatingActionsMenu) rootView.findViewById(R.id.multiple_actions_down);

Now i what to put the button on the left side, because by default is on the right side.

Thanks

**Comment by chalup** [comment]
Just to be clear: you want the buttons' labels to be on the right sides of the buttons?

**Comment by PJFonseca** [comment]
No. I what the whole button to be moved to the left side of the screen instead of the right side. 

I what my app to be good for the people that write with the left hand.

**Comment by chalup** [comment]
`layout_alignParentLeft` should work. Note that it's not an attrobute of any View from this library it comes from a standard `RelativeLayout` from Android SDK.
