### ISSUE TITLE
E/﹕ glEndTilingQCOM: 0x502

### ISSUE THREAD

**Issue by aristide** [futuresimple/android-floating-action-button#130]
each time i click on a floatingbutton I get this error : E/﹕ glEndTilingQCOM: 0x502
is it normal?
I'm running in debug mode

**Comment by chalup** [comment]
Not normal at all. Which version of library do you use? On what device do
you see this error?

**Comment by chalup** [comment]
There was no response for over a month, I'm closing this issue for now. Please let me know if the problem still occurs.
