### ISSUE TITLE
fab_labelsPosition is not recognized by Android Studio

### ISSUE THREAD

**Issue by ZaLeXemre** [futuresimple/android-floating-action-button#134]
Hi, i have compiled ver 1.7 through graddle but the fab_labelsPosition is not recognized.

**Comment by chalup** [comment]
That's because it's not released yet. I'll push it to Maven Central as 1.8
in the next few days.

**Comment by ZaLeXemre** [comment]
Oh, i got confused than :) Anyway, thats great :+1:
