### ISSUE TITLE
FAM colors in Java.

### ISSUE THREAD

**Issue by JonathanMerritt** [futuresimple/android-floating-action-button#136]
Is there a way to set the FAM colors and other attributes in Java?

Thank You.

**Comment by chalup** [comment]
Not yet. There's already an issue for this (#49).

**Comment by JonathanMerritt** [comment]
Oops. I did see that, but wasn't aware what it meant. Sorry.

**Comment by JonathanMerritt** [comment]
I made up a easy fix till programmatic support for FAMs is introduced.

I simply made a layout to hold my FAMs, made them GONE. Then I simply include that to whatever layout I need it in, then just set the FAM I need for that screen to VISIBLE. 

A tad clunky, but it works for the time being.
