### ISSUE TITLE
blue fab button

### ISSUE THREAD

**Issue by bassam200800** [futuresimple/android-floating-action-button#138]
Your button works perfect but I don't know why in this layout change the color to blue even if I put another color value could u help me plz and sorry for my bad English
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.Toolbar
        style="@style/ToolBarStyle"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/toolbar_actionbar"
        android:minHeight="@dimen/abc_action_bar_default_height_material"/>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?colorPrimary"
        android:orientation="vertical"
        android:paddingBottom="60dp"
        android:layout_below="@+id/toolbar_actionbar"
        android:id="@+id/header"
        android:paddingLeft="72dp"
        android:paddingRight="16dp">

        <com.rengwuxian.materialedittext.MaterialEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@string/username_hint_string"
            android:textCursorDrawable="@null"
            app:baseColor="@android:color/white"
            app:floatingLabel="highlight"
            app:primaryColor="?colorAccent" />

        <com.rengwuxian.materialedittext.MaterialEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@string/passowrd_hint_string"
            android:textCursorDrawable="@null"
            app:baseColor="@android:color/white"
            app:floatingLabel="highlight"
            app:primaryColor="?colorAccent" />

    </LinearLayout>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/header"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:paddingLeft="72dp"
        android:paddingRight="16dp">

        <LinearLayout
            android:id="@+id/body"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <com.rengwuxian.materialedittext.MaterialEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/age_et"
                android:hint="@string/age_hint_string"
                app:floatingLabel="highlight"
                android:textCursorDrawable="@null"
                android:inputType="numberDecimal"
                android:gravity="center_vertical|left"
                app:accentTypeface="fonts/NotoSans/NotoSans-Regular.ttf"
                app:baseColor="@color/text_icon_colo"
                app:errorColor="@color/error_color"
                app:primaryColor="?colorAccent"
                app:singleLineEllipsis="true"/>

            <com.rengwuxian.materialedittext.MaterialEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/nationality_et"
                android:hint="@string/nationality_hint_string"
                app:floatingLabel="highlight"
                android:textCursorDrawable="@null"
                android:gravity="center_vertical|left"
                app:accentTypeface="fonts/NotoSans/NotoSans-Regular.ttf"
                app:baseColor="@color/text_icon_colo"
                app:errorColor="@color/error_color"
                app:primaryColor="?colorAccent"
                app:singleLineEllipsis="true"/>

            <com.rengwuxian.materialedittext.MaterialEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/address_et"
                android:hint="@string/address_hint_string"
                app:floatingLabel="highlight"
                android:textCursorDrawable="@null"
                android:gravity="center_vertical|left"
                app:accentTypeface="fonts/NotoSans/NotoSans-Regular.ttf"
                app:baseColor="@color/text_icon_colo"
                app:errorColor="@color/error_color"
                app:primaryColor="?colorAccent"
                app:singleLineEllipsis="true"/>

            <com.rengwuxian.materialedittext.MaterialEditText
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="phone"
                android:id="@+id/phone_et"
                android:hint="@string/phone_hint_string"
                app:floatingLabel="highlight"
                android:textCursorDrawable="@null"
                android:gravity="center_vertical|left"
                app:accentTypeface="fonts/NotoSans/NotoSans-Regular.ttf"
                app:baseColor="@color/text_icon_colo"
                app:errorColor="@color/error_color"
                app:primaryColor="?colorAccent"
                app:singleLineEllipsis="true"/>

        </LinearLayout>

    </ScrollView>

    <com.getbase.floatingactionbutton.FloatingActionButton
        android:id="@+id/ad_float_btn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        fab:fab_icon="@mipmap/ic_check"
        fab:fab_colorNormal="@color/myDarkAccentColor"
        fab:fab_colorPressed="@color/myAccentColor"
        android:layout_alignParentRight="true"
        android:layout_alignBottom="@id/header"
        android:layout_marginBottom="-39dp"
        android:layout_marginRight="20dp" />

</RelativeLayout>

**Comment by chalup** [comment]
You use invalid xml namespace. Just use existing `app` namespace or change the `fab` to `"http://schemas.android.com/apk/res-auto"`
