### ISSUE TITLE
Not able to click the views beneath the FAB

### ISSUE THREAD

**Issue by sayoojvalsan-demandmedia** [futuresimple/android-floating-action-button#139]
When the FAB is in closed state, the views beneath it doesn't get the touch input.

If you enable show layout bounds from the developer options settings, you could see an invisible view container for the FAB. This view consumes the touch. Is there any way to fix this ? or work around ?

**Comment by chalup** [comment]
Which version of library do you use? Can you modify the sample app from this repo to reproduce this issue?

**Comment by sayoojvalsan-demandmedia** [comment]
I am using '1.7.0'

**Comment by sayoojvalsan-demandmedia** [comment]
I am not able to reproduce the issue in the sample project.

**Comment by sayoojvalsan-demandmedia** [comment]
The issue happens happen you set OnClick Listener to the Component. Was able to reproduce it.

**Comment by sayoojvalsan-demandmedia** [comment]
I think I am not supposed to set OnClick listener to the Menu Button. If I do, it consumes the event and any view underneath it doesn't receive the click.
