### ISSUE TITLE
Listener for plus icon click

### ISSUE THREAD

**Issue by ParinParikh** [futuresimple/android-floating-action-button#145]
Is there a way I can add a listener to clicking of the plus icon?

**Comment by HamzehSoboh** [comment]
I really need this too.

**Comment by HamzehSoboh** [comment]
I could do it, it was simple:

        floatingActionsMenu.findViewById(R.id.fab_expand_menu_button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                floatingActionsMenu.toggle();
            }
        });

**Comment by chalup** [comment]
Out of curiosity: why do you need this? There is `OnFloatingActionsMenuUpdateListener` with `onMenuExpanded`/`onMenuCollapsed` callbacks.

**Comment by ParinParikh** [comment]
@chalup Yep I used that.

I wanted to add a screen blur animation every time the menu collapsed/expanded.
