### ISSUE TITLE
FloatingActionsMenu doesn`t animate when open/close on Release build type

### ISSUE THREAD

**Issue by supervital** [futuresimple/android-floating-action-button#147]
FloatingActionsMenu doesn`t animate when open/close on Release build type. On debug type works ok.

**Comment by chalup** [comment]
If you use gradle, everything should work out of the box. If you use other build system, you have to add [android-floating-action-button/library/proguard-rules.pro](https://github.com/futuresimple/android-floating-action-button/blob/master/library/proguard-rules.pro) to your proguard configuration.

**Comment by supervital** [comment]
Thanks for response. We use Gradle, and I added your lib as Module. proguard-rules.pro file is added. Also I added code below in proguard-rules.pro in App module.
 -keepclassmembers class fqcn.of.javascript.interface.for.webview {
    	 public *;
    }

Still doesn`t animate.

**Comment by chalup** [comment]
Crap, posted wrong path in my previous response. I meant you should use [android-floating-action-button/library/consumer-proguard-rules.pro](https://github.com/futuresimple/android-floating-action-button/blob/master/library/consumer-proguard-rules.pro) rules.

**Comment by supervital** [comment]
Yeah. Thanks a lot! Works great!
