### ISSUE TITLE
Floating Menu EXPAND_LEFT size problem

### ISSUE THREAD

**Issue by pedrowav** [futuresimple/android-floating-action-button#149]
When set expand direction to EXPAND_LEFT the size of the floating menú is wrong unless i call expand() next in the same method (in my case, i'm calling it in the onCreate() method of the activity).

**Comment by chalup** [comment]
I cannot reproduce it. Can you modify sample app on `issue-149` branch to demonstrate what's wrong?

**Comment by chalup** [comment]
No response, closing.
