### ISSUE TITLE
Wiki Needed

### ISSUE THREAD

**Issue by AMQTech** [futuresimple/android-floating-action-button#154]
I'd like to make a Wiki since the Readme just kind of shows what this library can do. Is this OK with the owner?

**Comment by chalup** [comment]
What would you like to include in this wiki and how would you like to modify the readme?

**Comment by AMQTech** [comment]
Just include code examples...like other libraries have.

**Comment by chalup** [comment]
I think wiki is necessary for projects like RxJava or Dagger. For UI lib implementing a circular button the good sample/demo app linked from readme should be enough.

**Comment by AMQTech** [comment]
Alright...if you say so!
