### ISSUE TITLE
Is there an easy way to detect a click on a FloatingActionsMenu?

### ISSUE THREAD

**Issue by loeschg** [futuresimple/android-floating-action-button#156]
Setting an onClickListener and onTouchListener doesn't do anything because I'd assume the touch is consumed.

**Comment by chalup** [comment]
Have you checked the `onMenuCollapsed`/`onMenuExpanded` callbacks from `OnFloatingActionsMenuUpdateListener`?

**Comment by loeschg** [comment]
@chalup nope! Thanks.
