### ISSUE TITLE
sliding effects

### ISSUE THREAD

**Issue by jjhesk** [futuresimple/android-floating-action-button#159]
does it have a sliding effects to work with the list view. when the list is scrolling down then the floating button will slide out from the bottom.

**Comment by gschier** [comment]
:+1:

**Comment by FranclisJunior** [comment]
how enable?

**Comment by csabatini** [comment]
#1 

> It's addressed in 'caveats' section in readme:

> "Unlike some other FloatingActionButton libraries this library doesn't implement "quick return" pattern, i.e. hiding the button on scrolling down and showing it on scrolling up. That's intentional, I think that should be responsibility of another component, not the button itself."

**Comment by chalup** [comment]
@csabatini got this right. I intend to change current sample app into "sandbox" app and create a separate sample app with "I want my FAB to behave like FABs from Google+/Inbox/Trello/whatever" and show how to achieve this effect in this sample app, not in the library itself.
