### ISSUE TITLE
Bug with showing FAB menu

### ISSUE THREAD

**Issue by ormoru** [futuresimple/android-floating-action-button#161]
Hi,
 I create main layout, where I include FAB layout. Sometimes if FAB menu is visibel, hide under the EditText. And I dont know, why? Thank you for some ideas.

**Main layout**
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:id="@+id/root"
        style="@style/layout_root"
        tools:context=".FieldNotesList">

        <include layout="@layout/toolbar"/>

        <LinearLayout
            style="@style/layout_main">

            ...
            </LinearLayout>

            <ScrollView
                android:id="@+id/scroll"
                style="@style/layout_main_padding">

                <LinearLayout
                    android:orientation="vertical"
                    android:layout_width="fill_parent"
                    android:layout_height="wrap_content">

                    <EditText
                        android:id="@+id/edit_note"
                        style="@style/detail_edit_note"
                        android:text="@string/value_note"/>

                    <TextView
                        android:layout_width="fill_parent"
                        android:layout_height="5dp"/>
                </LinearLayout>
            </ScrollView>
        </LinearLayout>
    </LinearLayout>

    <include layout="@layout/fab_detail"/>
</FrameLayout>

**FAB layout**

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/layout_fab">

    <com.getbase.floatingactionbutton.FloatingActionsMenu
        android:id="@+id/fab_multiple_actions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginBottom="@dimen/size_16"
        android:layout_marginRight="@dimen/size_16"
        android:layout_marginEnd="@dimen/size_16"
        fab:fab_addButtonColorNormal="@color/fab_color_normal"
        fab:fab_addButtonColorPressed="@color/fab_color_pressed"
        fab:fab_addButtonPlusIconColor="@color/white"
        fab:fab_labelStyle="@style/fab_label">

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_action_set_favorite"
            android:src="@drawable/ic_favorite_white_24dp"
            fab:fab_title="@string/check_as_favorite"
            style="@style/fab_button"/>

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_action_voice"
            android:src="@drawable/ic_microphone_white_24dp"
            fab:fab_title="@string/speak"
            style="@style/fab_button"/>

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab_action_change_date"
            android:src="@drawable/ic_calendar_white_24dp"
            fab:fab_title="@string/change_date"
            style="@style/fab_button"/>
    </com.getbase.floatingactionbutton.FloatingActionsMenu>
</RelativeLayout>

**Bug**
![bug](https://cloud.githubusercontent.com/assets/10798176/6770262/3d5263b8-d0bb-11e4-807c-414263a4744e.png)

**Comment by efecannn** [comment]
+1

**Comment by balasaheb143** [comment]
same issue

**Comment by chalup** [comment]
Can you modify sample app to reproduce this issue?

**Comment by chalup** [comment]
No repsonse, closing. I'll reopen the issue if more info is provided.

**Comment by balasaheb143** [comment]
if parent layout is LinerLayout FAB menu not showing properly ,I change LinerLayout to RelativeLayout and it solve my issue

**Comment by chalup** [comment]
It explains why you had the problems. LinearLayout is for placing items next to each other, and the FloatingActionsMenu is, well, *floating* over the content :)
