### ISSUE TITLE
Font awesome Drawable ?

### ISSUE THREAD

**Issue by neoteknic** [futuresimple/android-floating-action-button#166]
When I add a font awesome Icon with : 

IconDrawable icon = new IconDrawable(getActivity(), Iconify.IconValue.fa_send).colorRes(R.color.white).sizeDp(20);
button.setIconDrawable(icon);

The icon is never centered, it's alwayson the top left corner. How to center the IconDrawable ?
Can you add a simple parameter to center a drawable ?

**Comment by chalup** [comment]
Looks like a duplicate of #89
