### ISSUE TITLE
Possible error:"Could not find class 'android.graphics.drawable.RippleDrawable' ... "

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [futuresimple/android-floating-action-button#175]
Sometimes I get this error in the logs:

E/dalvikvm(10222): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.getbase.floatingactionbutton.FloatingActionButton.setBackgroundCompat

Please check it out.

**Comment by chalup** [comment]
I have no idea how this might happen, I do not reference RippleDrawables anywhere in my code. I have also run the sample app on pre-Lollipop devices and nothing like this ever happened.

Which version of library do you use? Can you add a reproduction steps to sample app?

**Comment by AndroidDeveloperLB** [comment]
@chalup Oh, you are correct. I did this:
https://github.com/futuresimple/android-floating-action-button/issues/35

Can you tell me what could cause it?

**Comment by chalup** [comment]
The code you posted in #35 looks ok, but I didn't dig into this issue. I'll handle this issue with ripple/elevation support.

**Comment by AndroidDeveloperLB** [comment]
ok, sorry for this, and thank you.
