### ISSUE TITLE
change the FloatingActionsMenu icon

### ISSUE THREAD

**Issue by idanbar134** [futuresimple/android-floating-action-button#176]
Hello,

can i change the FloatingActionsMenu icon to custom icon?

Thanks,
Idan Ayalon

**Comment by Andrew-Quebe** [comment]
Check this issue out: https://github.com/futuresimple/android-floating-action-button/issues/56

**Comment by chalup** [comment]
Duplicate of #56.

**Comment by jemshit** [comment]
@chalup add option to change fab menu icon, ecen it is not great for now, just plus icon is not enough
