### ISSUE TITLE
Change Normal & Pressed Color Programatically

### ISSUE THREAD

**Issue by aritraroy** [futuresimple/android-floating-action-button#178]
Is there a way to change the color of the Floating Menu programmatically using setNormalColor or setPressedColor methods. It is very important for me as I want to change the colors at run-time.

**Comment by chalup** [comment]
Duplicate of #49

**Comment by dkdilipkumar** [comment]
I'm also need to change the "fab_addButtonColorPressed" color programatically.

**Comment by dkdilipkumar** [comment]
I also need to change the "fab_addButtonColorPressed" pragmatically.
