### ISSUE TITLE
Collapse on fam with parameter to collapse immediately

### ISSUE THREAD

**Issue by Ph1b** [futuresimple/android-floating-action-button#180]
It would be great to have the collapse take a boolean (boolean immediately) to collapse immediately and without animation.
Or just have a new method called collapseImmediately for API backwards compatibility. Or take a add a new method with parameter and deprecate the old one.

This is useful, because when you start another activity from a FAB in an FAM and then return, you want to collapse the FAM in onResume(). You can do so but this causes some ugly visual blink since the collapse is visible for a fraction of a secound.

**Comment by chalup** [comment]
Agreed.

**Comment by chalup** [comment]
Added `collapseImmediately()` method.
