### ISSUE TITLE
Integration with eclipse

### ISSUE THREAD

**Issue by rmuhamed** [futuresimple/android-floating-action-button#181]
There is a way to integrate into Android Project using eclipse without maven?

My idea is to add as a third party project, is that possible?

Thanks in advance

Regards

**Comment by chalup** [comment]
It should be possible, but I don't know exact steps. You should really consider moving to Android Studio, or at least using some maven/gradle plugin for eclipse.

**Comment by rmuhamed** [comment]
Thanks for your advice, 

I made a switch to Android studio a few months ago. Was the best solution i thik so...
