### ISSUE TITLE
Impossible to import the project in gradle. Error Code: 	-1073741819

### ISSUE THREAD

**Issue by ChristopheVersieux** [futuresimple/android-floating-action-button#183]
Hello,

I just added the project into Android studio, like many other libs with this line:

    compile 'com.getbase:floatingactionbutton:1.9.0'

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\Program Files (x86)\Android\sdk\build-tools\android-4.4W\aapt.exe package -f --no-crunch -I C:\Program Files (x86)\Android\sdk\platforms\android-21\android.jar -M C:\Users\MyApp\Google Drive\AndroidStudioProjects\MyApp\app\build\intermediates\manifests\full\debug\AndroidManifest.xml -S C:\Users\MyApp\Google Drive\AndroidStudioProjects\MyApp\app\build\intermediates\res\debug -A C:\Users\MyApp\Google Drive\AndroidStudioProjects\MyApp\app\build\intermediates\assets\debug -m -J C:\Users\MyApp\Google Drive\AndroidStudioProjects\MyApp\app\build\generated\source\r\debug -F C:\Users\MyApp\Google Drive\AndroidStudioProjects\MyApp\app\build\intermediates\res\resources-debug.ap_ --debug-mode --custom-package com.MyApp.MyApps -0 apk --output-text-symbols C:\Users\MyApp\Google Drive\AndroidStudioProjects\MyApp\app\build\intermediates\symbols\debug
Error Code:
	-1073741819

Any idea what could be wrong? Other libs are imported without any issue

**Comment by KReguieg** [comment]
Hi,

I had to use this
    compile 'com.android.support:appcompat-v7:22.0.0'
in my dependencies, do you use it?

**Comment by ChristopheVersieux** [comment]
I imported the freshly released 22.1.0, maybe there is an incompatibility between them?
Will try to import 22.0.0 tonight and see if there are no more crashes.
Thanks

**Comment by ChristopheVersieux** [comment]
I tried to import appcompat-v7:22.0.0 instead of 22.1.0 but this doesn't change anything.

Really strange, because it seems I am the only one to have this issue and usually import a lot of libs without issue..

**Comment by kayanalmeida** [comment]
Also having this issue, tried to clone this repository import using `compile project()`, no success.

**Comment by vimoxshah** [comment]
i have same issue.but i can not solve t.please any one have solution than tell.what should i do?

**Comment by mallorente** [comment]
I have the same issue. Finally I have switched to a differen FAB implementation.

**Comment by chalup** [comment]
Can you post your build.gradle as a gist and add link it here?

**Comment by chalup** [comment]
No response, closing.
