### ISSUE TITLE
Can't import library  Could not find com.android.support:support-annotations:22.0.0.

### ISSUE THREAD

**Issue by BoldijarPaul** [futuresimple/android-floating-action-button#185]
compile 'com.getbase:floatingactionbutton:1.9.0'

I get error when syncing with gradle

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:support-annotations:22.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.pom
         https://jcenter.bintray.com/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.jar
         file:/D:/Android/Android SDK/extras/android/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.pom
         file:/D:/Android/Android SDK/extras/android/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.jar
         file:/D:/Android/Android SDK/extras/google/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.pom
         file:/D:/Android/Android SDK/extras/google/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.jar
     Required by:
         projectname:app:unspecified > com.android.support:recyclerview-v7:21.0.3
         projectname:app:unspecified > com.android.support:support-v4:21.0.3
   > Could not find com.android.support:support-annotations:22.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.pom
         https://jcenter.bintray.com/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.jar
         file:/D:/Android/Android SDK/extras/android/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.pom
         file:/D:/Android/Android SDK/extras/android/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.jar
         file:/D:/Android/Android SDK/extras/google/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.pom
         file:/D:/Android/Android SDK/extras/google/m2repository/com/android/support/support-annotations/22.0.0/support-annotations-22.0.0.jar
     Required by:
         projectname:app:unspecified > net.i2p.android.ext:floatingactionbutton:1.9.0

**Comment by svanegas** [comment]
+1

**Comment by hkurra** [comment]
Update your Android support library to 22.1.1

**Comment by svanegas** [comment]
@hkurra Thank you, it worked.
I updated my Android packages as stated here: http://stackoverflow.com/a/20830540 so that I could use 22.1.1 support libraries. Then, I added the android-floating-action-button dependency, rebuilt the project and it worked.
