### ISSUE TITLE
How can I use 'setColorFilter' for FloatingActionButton?

### ISSUE THREAD

**Issue by MewX** [futuresimple/android-floating-action-button#193]
I want to change color of my icon, is there a method to achieve that?

**Comment by KReguieg** [comment]
At the moment there is no way to achieve this. I just changed the color of my icon in illustrator and added it to my project. If you use google icons https://github.com/google/material-design-icons you can download the .svg file and style it like you want! :)

**Comment by MewX** [comment]
Fine, thank you!
