### ISSUE TITLE
Can't build gradle

### ISSUE THREAD

**Issue by vimoxshah** [futuresimple/android-floating-action-button#198]
It gives error while building gradle file after adding your dependency

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\android_sdk\android sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

What should i do?

**Comment by SilverFoxA** [comment]
I am also facing the same problem

**Comment by ramabmtr** [comment]
try to clean or rebuild your project

**Comment by chalup** [comment]
Can you list your other dependencies? Preferably just post your build.gradle.

**Comment by chalup** [comment]
No response, closing.
