### ISSUE TITLE
running gradle error

### ISSUE THREAD

**Issue by arifardians** [futuresimple/android-floating-action-button#205]
Hi chalup, thanks for create this awesome project.. :dancer: 
but I have problem when running build.gradle with this depedencies : 
dependencies {
    compile 'com.getbase:floatingactionbutton:1.9.0'
}

error was cause by :
![gradle error](https://cloud.githubusercontent.com/assets/6582334/7862159/5dea4a76-057e-11e5-87f8-8ec845f92a74.JPG)

Do you have any solution for this problem.? 
Thanks  :+1:

**Comment by chalup** [comment]
Make sure you have mavenLocal() repository defined in your build.gradle. If
this doesn't solve the problem, try installing all updates available in
Android SDK Manager. Let me know if this helps.

**Comment by arifardians** [comment]
I have add mavelLocal() repository in my build.gradle, but still not work because I there is no android.support-annotations library in my local maven too. And I have update my SDK manager too. But still not working. 
Is it happened cause maven central does not have android.support-annotations repository?

**Comment by arifardians** [comment]
It seem like a bug of eclipse gradle integration plugin. There is no android support annotations 22.0.0 in my maven local, so I add manually from 
<Android SDK Directory>/extras/android/m2repository/com/android/support/support-annotations/22.0.0
to my local maven repository. Thanks for helping :)
