### ISSUE TITLE
Use "icons-fonts" for Action Button Icon

### ISSUE THREAD

**Issue by albaraamishlawi** [futuresimple/android-floating-action-button#206]
Is it possible to use icons fonts for the Action Button Icon.
For example, I tried this library: https://github.com/Malinskiy/android-material-icons
```
FloatingActionButton btnTest = view.findViewById(R.id.btn_test);
btnTest.setIconDrawable(new IconDrawable(getActivity(), Iconify.IconValue.md_assignment_ind));
```
 but it doesn't work, size doesn't fit.

It would be great if it's possible to implement.

**Comment by chalup** [comment]
This is a bug in the library you use, specifically `IconDrawable.draw` assumes that the `getBounds` return `Rect` starting at `(0, 0)` coords.

**Comment by albaraamishlawi** [comment]
Thanks I Just noticed that now :+1:
