### ISSUE TITLE
Readded button don't show label - Tag not cleared when removing button from FloatingActionMenu 

### ISSUE THREAD

**Issue by guillaumyle** [futuresimple/android-floating-action-button#211]
I have a FAB that is dynamically added/removed from a FloatingActionMenu.
The first time it is added, everything works fine, but if it is removed and added again, the label won't show.
I dug around and found this was due to the check on the Tag of the button during the createLabels().
As the button went through this step once, the label's TextView is not recreated, so I have to manually set the tag "fab_label" of my button to null when I remove it from the FAM to make sure it will be correctly reattach later.

Not sure if this has other consequences.

**Comment by chalup** [comment]
Thanks for a great bug report! Fixed in `1.9.1`.
