### ISSUE TITLE
Label not visible even after setting by fab_title

### ISSUE THREAD

**Issue by irtefa** [futuresimple/android-floating-action-button#212]
<com.getbase.floatingactionbutton.FloatingActionsMenu
        android:id="@+id/action_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_marginLeft="16dp"
        android:layout_marginStart="16dp"
        fab:fab_addButtonColorNormal="@color/brand_blue"
        fab:fab_addButtonColorPressed="@color/white"
        fab:fab_addButtonPlusIconColor="@color/white"
        fab:fab_labelsPosition="left">

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/send_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_colorNormal="@color/brand_blue"
            fab:fab_title="Action A"
            fab:fab_colorPressed="@color/white"/>

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/redeem_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_colorNormal="@color/brand_blue"
            fab:fab_title="Action with a very long name that won\'t fit on the screen"
            fab:fab_colorPressed="@color/white"/>

    </com.getbase.floatingactionbutton.FloatingActionsMenu>

**Comment by young-Simba** [comment]
I am also a bit confused as to how to show labels beside the buttons. Is there a method for this or an xml attribute?

**Comment by chalup** [comment]
@young-Simba you have to set `fab:fab_labelStyle` on your `FloatingActionsMenu`

**Comment by young-Simba** [comment]
@chalup thanks alot

**Comment by awong1900** [comment]
same question. thanks.

**Comment by achavhan** [comment]
label not visible plz help

    <com.getbase.floatingactionbutton.FloatingActionsMenu
        android:id="@+id/multiple_actions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        fab:fab_labelStyle="@style/menu_labels_style"
        android:layout_marginBottom="16dp"
        android:layout_marginRight="8dp"
        android:layout_marginEnd="8dp"
        custom:fab_labelsPosition="left"
        >
        
    </com.getbase.floatingactionbutton.FloatingActionsMenu>

    <style name="menu_labels_style">
        <item name="android:background">@drawable/fab_label_background</item>
        <item name="android:textColor">@color/white</item>
    </style>

        FloatingActionButton zz = new FloatingActionButton(getBaseContext());
        zz.setSize(FloatingActionButton.SIZE_MINI);
        zz.setIcon(R.drawable.smart_shopping_white_min);
        zz.setStrokeVisible(true);
        zz.setTitle("Smart Shopping");
        zz.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                menuMultipleActions.collapse();

            }
        });
        menuMultipleActions.addButton(zz);

**Comment by achavhan** [comment]
just found ans on another thread 

xmlns:fab were
xmlns:fab="http://schemas.android.com/tools" (auto import)
This import fix is fixed the issue, labels are now visible:
xmlns:fab="http://schemas.android.com/apk/res-auto"

**Comment by gabriellferreira** [comment]
@achavhan you should win a prize, 2 hours trying make this lib to work
someone should write this down on Wiki

**Comment by neolio42** [comment]
My labels are not visible with : 
xmlns:fab="http://schemas.android.com/apk/res-auto"
fab:fab_labelsPosition="right" and fab:fab_labelStyle setted

Any good idea ?

**Comment by neolio42** [comment]
My mistake, use fab:fab_title instand of fab:fab_label
And all is ok

**Comment by isuPatches** [comment]
@achavhan you're a hero
