### ISSUE TITLE
is it possible to change button menu color when it is expanded?

### ISSUE THREAD

**Issue by newUserKhd** [futuresimple/android-floating-action-button#213]
Hi, I would like to set a different color to my menu button when it is expanded. Is it possible with this library? I only know these options: 

        fab:fab_addButtonColorNormal="@color/black"
        fab:fab_addButtonColorPressed="@color/red"

is there any way to change it from the code?

Thank you very much!

**Comment by Hadjimina** [comment]
+1

**Comment by chalup** [comment]
This will be possible once #49 is implemented.
