### ISSUE TITLE
FloatingActionButtonMenu over ListView : touch issues

### ISSUE THREAD

**Issue by fred8** [futuresimple/android-floating-action-button#215]
I have an issue when I'm trying to add a floating action button menu over a list.
It seems that the region of the menu is really big even when the menu is collapsed. When I touch in that part, the listview doesn't get the touch events. As the result of it, I can't scroll or click on one item of my list. Any ideas or workaround?

Thx

**Comment by chalup** [comment]
Sounds like you set the onClickListener on FloatingActionsMenu.

If that's not the case, can you create a pull request which demonstrates the issue inside sample applications?

**Comment by fred8** [comment]
@chalup Thank you for your help! I actually find the issue; it's not related to your code.

**Comment by jeanvallon** [comment]
Hey, could you explain how you figured this out please ? :)

**Comment by thelou1s** [comment]
same problem, with no click listener. how you figured this out please ? :)

**Comment by 18616505009** [comment]
same problem,solved by myself
![image](https://user-images.githubusercontent.com/17908385/41404049-cd403236-6ff8-11e8-8648-8c007071733f.png)
