### ISSUE TITLE
FloatingActionButtonMenu with different icon

### ISSUE THREAD

**Issue by jamoque** [futuresimple/android-floating-action-button#216]
Is it possible to create a FloatingActionButtonMenu item with an icon that isn't a plus. Specifically I was hoping to use a vertical ellipsis like the one that would normally be seen in the ActionBar. I have tried looking through the source, but with no luck. Any help is appreciated!

**Comment by koustuvsinha** [comment]
:+1: Need this api, both from xml and programmatically

**Comment by brandoFS** [comment]
I would also like this

**Comment by chalup** [comment]
Duplicate of #56

**Comment by Aasif312** [comment]
This should work

       floatingActionMenu.setIconAnimated(false);

       floatingActionMenu.setOnMenuToggleListener(new FloatingActionMenu.OnMenuToggleListener() {
            @Override
            public void onMenuToggle(boolean opened) {
                if (opened)
                {
                		floatingActionMenu.getMenuIconView().invalidateDrawable
                		(
          		        floatingActionMenu.getMenuIconView().getDrawable()  
          		        );
        			    floatingActionMenu.getMenuIconView().setImageBitmap(
                			BitmapFactory.decodeResource(
                        			getResources(), R.drawable.<YOUR_DRAWABLE_ID>
                					)
        				);
                }
                    
                else
                {
                	floatingActionMenu.getMenuIconView().invalidateDrawable
                		(
          		        floatingActionMenu.getMenuIconView().getDrawable()  
          		        );
        			    floatingActionMenu.getMenuIconView().setImageBitmap(
                			BitmapFactory.decodeResource(
                        			getResources(), R.drawable.<YOUR_DRAWABLE_ID>
                					)
        				);

                }
                     
            }
        });
