### ISSUE TITLE
Failed to resolve: com.getbase:floatingactionbutton:1.9.1

### ISSUE THREAD

**Issue by galvanu** [futuresimple/android-floating-action-button#219]
I've just added the compile line to my build.gradle file like this:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile 'com.android.support:recyclerview-v7:21.0.+'

    compile 'com.getbase:floatingactionbutton:1.9.1'
}

and I get the next error:
Failed to resolve: com.getbase:floatingactionbutton:1.9.1

Do I need to add anything else in order to user the library?

**Comment by koustuvsinha** [comment]
make sure you have `jcenter` and `mavenCentral` specified in build.gradle like this : 
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

**Comment by galvanu** [comment]
Thanks!

**Comment by Puspharaj** [comment]
I have added this to my root build.gradle file. Still error pop's up.

**Comment by koustuvsinha** [comment]
@Puspharaj add this to your module build.gradle file, not the root one
