### ISSUE TITLE
Cannot resolve  'com.getbase:floatingactionbutton:1.9.1'?

### ISSUE THREAD

**Issue by ArunPandiyan** [futuresimple/android-floating-action-button#224]
When i put it in the gradle file, when i'm beginning to build gradle, it says cannot resolve compile 'com.getbase:floatingactionbutton:1.9.1'?

**Comment by chalup** [comment]
It's available on Maven Central (http://search.maven.org/#artifactdetails%7Ccom.getbase%7Cfloatingactionbutton%7C1.9.1%7Caar), check your `repositories` section in `build.gradle`.

**Comment by chalup** [comment]
No response, closing.

**Comment by ArunPandiyan** [comment]
Sorry i'm not available on internet for few days. but your solution did work me. Thanks anyway !
