### ISSUE TITLE
FAB drag and drop function

### ISSUE THREAD

**Issue by chrisonline** [futuresimple/android-floating-action-button#233]
Can you add a drag and drop function to the FAB?
I have the problem that the FAB is covering some infos on some screens amount of data.
It would be great if the user can drag and drop the FAB to the left side.

**Comment by chalup** [comment]
It should be possible to implement this behavior on top of this library, so I think it should not be a part of the library. Let me know if you have any problems with implementation.

BTW: I think the Google design guidelines suggest adding the bottom padding to your data to prevent this UX issue.

**Comment by hdmor** [comment]
maybe this page help you ---> http://qaru.site/questions/14383370/android-movabledraggable-floating-action-button-fab
