### ISSUE TITLE
SwipeRefreshLayout (v4 support library)

### ISSUE THREAD

**Issue by paolinho91** [futuresimple/android-floating-action-button#236]
Hi, when i have tried to add SwipeRefreshLayout instead of RelativeLayout, the main button become not clickable. I'm wrong or this layout is not supported?
Thanks

**Comment by chalup** [comment]
I just replaced main layout of MainActivity in sample app with SwipeRefreshLayout and everything seems to be working. Can you try to reproduce this issue within the sample app?

**Comment by paolinho91** [comment]
I have added SwipeRefreshLayout like root layout, and it works! Probably it was a my stupid mistake! Thanks

**Comment by paolinho91** [comment]
ah, congratulation for this work! Nice job!
