### ISSUE TITLE
AddFloatingActionButton cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by longnbse02652** [futuresimple/android-floating-action-button#244]
This is in XML:
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="example.com.demoapp.activity.CategoryFragment">

    <GridView
        android:id="@+id/gridViewCategory"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:clickable="true"
        android:columnWidth="160px"
        android:drawSelectorOnTop="true"
        android:focusable="true"
        android:gravity="center"
        android:numColumns="2"
        android:stretchMode="columnWidth"></GridView>

    <com.getbase.floatingactionbutton.FloatingActionButton
        android:id="@+id/float_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="16dp"
        android:layout_marginEnd="16dp"
        android:layout_marginRight="16dp"
        fab:fab_addButtonColorNormal="@color/colorAccent"
        fab:fab_addButtonColorPressed="#00d3ee"
        fab:fab_addButtonPlusIconColor="#808080"
        fab:fab_labelStyle="@style/menu_labels_style">

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/float_camera"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_colorNormal="@color/colorAccent"
            fab:fab_colorPressed="#00d3ee"
            fab:fab_icon="@mipmap/ic_addmysen_camera"
            fab:fab_title="撮影" />

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/float_record"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_colorNormal="@color/colorAccent"
            fab:fab_colorPressed="#00d3ee"
            fab:fab_icon="@mipmap/ic_addmysen_camera"
            fab:fab_title="レコーダー" />

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/float_addSentences"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_colorNormal="@color/colorAccent"
            fab:fab_colorPressed="#00d3ee"
            fab:fab_icon="@mipmap/ic_addmysen_camera"
            fab:fab_title="新しい文章" />

    </com.getbase.floatingactionbutton.FloatingActionButton>

</FrameLayout>

In JAVA code : 
 public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_category, container, false);
        // Inflate the layout for this fragment
        GridView gridview = (GridView) view.findViewById(R.id.gridViewCategory);
     

        float_button = (FloatingActionsMenu) view.findViewById(R.id.float_button);
        FloatingActionButton float_camera = (FloatingActionButton) view.findViewById(R.id.float_camera);
        FloatingActionButton float_record = (FloatingActionButton) view.findViewById(R.id.float_record);
        FloatingActionButton float_newSentences = (FloatingActionButton) view.findViewById(R.id.float_addSentences);

        return view;
    }

**Comment by longnbse02652** [comment]
i do in fragment, someone can help me ? plzzz

**Comment by chalup** [comment]
View with id `float_button` should be `FloatingActionsMenu`, not `FloatingActionsButton`.
