### ISSUE TITLE
Is there a way to close the FAB after a option has been clicked?

### ISSUE THREAD

**Issue by 8BitYoda** [futuresimple/android-floating-action-button#245]
If its there I'm totally over looking it and a point in the right direction would be very helpful.

**Comment by ImTosS** [comment]
Let´s suppose that we have a layout.xml like this: 

     <com.getbase.floatingactionbutton.FloatingActionsMenu
        android:id="@+id/multiple_actions_menu"
        ...
        >

        <com.getbase.floatingactionbutton.FloatingActionButton
          android:id="@+id/action_one"
          ...
          ...
             />
     </com.getbase.floatingactionbutton.FloatingActionsMenu>
First you need to inflate your FloatingActionsMenu and your FloatingActionButton, then add an OnClickListener to your floatingActionButton and add this: floatingActionsMenu.collapse();

That´s all.

Hope it helps! :)

**Comment by 8BitYoda** [comment]
Thanks, Im not sure how or why, I managed to overlook/forget about .collapse(). One small addition to your code in case anyone is in the same boat as me. I had to put:

    final FloatingActionsMenu mFAB = (FloatingActionsMenu) findViewById(R.id.multiple_actions_menu);

then within the OnClickListener as you mentioned above added this:

    mFAB.collapse();
