### ISSUE TITLE
Unable to resolve dependency in build.gradle

### ISSUE THREAD

**Issue by pmk2429** [futuresimple/android-floating-action-button#249]
I tried adding the FAB  button dependency using gradle compile   
    'com.getbase:floatingactionbutton:1.10.0'   
but it did not work.
I am using gradle 2.4 with Android Studio version 1.3. 
It keeps on giving failure to resolve dependency error. 
Please help.

Thanks

**Comment by chalup** [comment]
What's in the `repositories` section in your `build.gradle`?

**Comment by pmk2429** [comment]
Its `jcenter()`. Its an exported eclipse project.

**Comment by chalup** [comment]
Strange, everything works for me in this setup. Can you post your gradle
files as a gist?

**Comment by pmk2429** [comment]
Here it is:

https://gist.github.com/pmk2429/975ba22efb70f42470ef

**Comment by chalup** [comment]
This section:

```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
    }
}
```

Specifies the repositories used for build script dependencies, i.e. where should the gradle look for android gradle plugin. You need to specify repositories for your app dependencies next to the dependencies section:

```gradle
repositories {
  jcenter()
}

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.google.android.gms:play-services:7.5.0'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile project(':fileChooser')
}
```

Let me know if this solves your problem.

**Comment by pmk2429** [comment]
Wow man. It did solve the problem. Super thanks!
