### ISSUE TITLE
Removing sample from production code

### ISSUE THREAD

**Issue by haibison** [futuresimple/android-floating-action-button#271]
Please remove `sample` from production code. For example currently `settings.gradle` contains:

```gradle
include ':library', ':sample'
```

However, it should be:

```gradle
include ':library'
```

Thank you.

**Comment by haibison** [comment]
My idea is to make new branch, maybe `sample`, and move `sample` folder to that branch...

**Comment by chalup** [comment]
Why do you think I should do this?

**Comment by haibison** [comment]
Oh, I think sample code should not be put into production. Normally people use the library code, not sample code. It's just my idea...

**Comment by chalup** [comment]
The sample code is not put onto classpath if you use this gradle configuration:

```groovy
dependencies {
    compile 'com.getbase:floatingactionbutton:1.10.1'
}
```
