### ISSUE TITLE
Attach to listview/recyclerview

### ISSUE THREAD

**Issue by melon-ruet** [futuresimple/android-floating-action-button#277]
Is it possible to attach fab to **listview** or **recyclerview** so while scrolling fab will be hidden?

**Comment by nitinjadhav** [comment]
yes... check sample example. FAB is attched to Recycleview.

On Tue, Feb 9, 2016 at 1:12 AM, Mahabubur Rahaman Melon <
notifications@github.com> wrote:

> Is it possible to attach fab to *listview* or *recyclerview* so while
> scrolling fab will be hidden?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/futuresimple/android-floating-action-button/issues/277>
> .
>



-- 
Regards ,
Nitin Jadhav

**Comment by melon-ruet** [comment]
I don't get any sample. Can u please give me a some code snippets?

**Comment by nitinjadhav** [comment]
Hi..

https://github.com/Clans/FloatingActionButton?files=1

Check this above github link.  Import project in Android studio.

They gave instructions how to add.

**Comment by noxevolution** [comment]
Sorry if it is a bad answer or not (Still a noob!!!!) but u can achieve this by using Quick Pattern Libs..

Here's one [](https://github.com/lawloretienne/QuickReturn)

and here's another [](https://github.com/felipecsl/QuickReturn)

The second one (I am using) does not support recyclerview though!!!
