### ISSUE TITLE
Adjust Icon in FloatingActionButton to occupy entire width and height?

### ISSUE THREAD

**Issue by jonamreddy** [futuresimple/android-floating-action-button#278]
I am using the _FloatingActionsMenu_ and under which there are two _FloatingActionButton_(s).

I am using a drawable icon for one of the _FloatingActionButton_.

Markup below.
```
<com.getbase.floatingactionbutton.FloatingActionsMenu
        android:id="@+id/multiple_actions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_margin="16dp"
        fab:fab_addButtonColorNormal="@color/white"
        fab:fab_addButtonColorPressed="@color/white_pressed"
        fab:fab_addButtonPlusIconColor="@color/half_black"
        fab:fab_labelStyle="@style/FABLabelStyle">

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/action_dry_cleaning"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_icon="@drawable/ic_dry_cleaning"
            fab:fab_colorNormal="@color/white"
            fab:fab_title="Dry Cleaning"
            fab:fab_size="mini"
            fab:fab_colorPressed="@color/white_pressed"/>

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/action_wash_and_iron"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            fab:fab_icon="@drawable/ic_add"
            fab:fab_colorNormal="@color/white"
            fab:fab_title="Wash and Iron"
            fab:fab_size="mini"
            fab:fab_colorPressed="@color/white_pressed"/>

</com.getbase.floatingactionbutton.FloatingActionsMenu>
```

UI below.
![image](https://cloud.githubusercontent.com/assets/10164566/12909744/5fabb11c-cf2a-11e5-9d70-76f63fa8244a.png)

I want the image in the first _FloatingActionButton_ to fitXY. How do i do this?

I have tried setting scaleType="fitXY". It doesn't work. Please Help.

Thank you.

**Comment by sytolk** [comment]
you can set this in values/dimens.xml
```xml
<resources>
    <dimen name="fab_margin">16dp</dimen>
    <dimen name="fab_icon_size">35dp</dimen>
</resources>
```

**Comment by jonamreddy** [comment]
Thanks @sytolk :)

**Comment by RupeshYadav** [comment]
Make this entry in dimens
 
`<dimen name="design_fab_image_size" tools:override="true">36dp</dimen>`

Ex
`<resources xmlns:tools="http://schemas.android.com/tools">
    <dimen name="fab_margin">16dp</dimen>
    
    <dimen name="design_fab_image_size" tools:override="true">42dp</dimen>

</resources>`

You can adjust its size according to your need.

**Comment by SenseChoi** [comment]
Thanks you are interest


-----------------------원본 메세지-----------------------

보낸사람: "RupeshYadav "<notifications@github.com>

받는사람: futuresimple/android-floating-action-button <android-floating-action-button@noreply.github.com>

참조: Subscribed <subscribed@noreply.github.com>

보낸시간: 2017-12-07 22:55:29 GMT +0900 (ROK)

제목: Re: [futuresimple/android-floating-action-button] Adjust Icon inFloatingActionButton to occupy entire width and height? (#278)
 
 
Make this entry in dimens
<dimen name="design_fab_image_size" tools:override="true">36dp</dimen>
Ex

`

16dp



42dp
`
You can adjust its size according to your need.

**Comment by MyGitUserAcc** [comment]
@sytolk But how to include these dimension to FloatingActionsMenu ?? Can u explain it more

**Comment by MyGitUserAcc** [comment]
@sytolk I want to reduce the spacing between FloatingActionsButton, How should i do this???
