### ISSUE TITLE
Hiding FloatingActionMenu

### ISSUE THREAD

**Issue by yenpei** [futuresimple/android-floating-action-button#279]
I have the MainActivity with FloatingActionsMenu. When I launch a ProfileFragment, I wish to hide the FloatingActionsMenu, how can I do that? 

![screenshot_2016-02-11-18-21-30](https://cloud.githubusercontent.com/assets/5976964/12974159/bfd99a40-d0ec-11e5-8273-71a6a5acfb27.png)

**Comment by yenpei** [comment]
Apparently I found the fix:
myFloatingActionsMenu.setVisibility(View.GONE);

**Comment by nilsi** [comment]
I would like to hide the menu as well but with a scale down effect. However that does not work well since the menu layout itself is bigger than the FAB layout so the FAB animates and moves up left creating a strange animation. This is the code I use:


```
fabLayout.animate()
     .scaleX(0f)
     .scaleY(0f)
     .alpha(0f)
         .setDuration(200)
     .setInterpolator(new FastOutSlowInInterpolator())
     .setListener(new AnimatorListenerAdapter() {
     @Override
     public void onAnimationStart(Animator animation) {

         }
 });

```

Has anyone figured out a better way?
