### ISSUE TITLE
Is it possible when clicked to FloatActionMenu open down ? 

### ISSUE THREAD

**Issue by emrekose26** [futuresimple/android-floating-action-button#311]
In my code `FloatActionMenu` position is top of the screen. I want to open down this menu. 
So my `FloatActionMenu` xml code like below 

    android:layout_alignTop="true"
    android:layout_alignParentRight="true"
 Is it possible ?

**Comment by harrygrifyndor** [comment]
add 
fab:fab_expandDirection="down"

**Comment by emrekose26** [comment]
Thanks @harrygrifyndor
