### ISSUE TITLE
Title and size

### ISSUE THREAD

**Issue by AshkanImmortal** [futuresimple/android-floating-action-button#79]
Hi, Great job, I added gradle and used your sample app code exactly in a sample, this is what happens in rendering view:
The following classes could not be instantiated:
- com.getbase.floatingactionbutton.FloatingActionsMenu (Open Class, Show Exception)
- com.getbase.floatingactionbutton.FloatingActionButton (Open Class, Show Exception)

Also attributes 
            fab:fab_title="Add me"
            fab:fab_size="mini"
doesnt work on layout like this nor java class with setTitle!
I get following error in build: 
Error:(22) No resource identifier found for attribute 'fab_title' in package 'com.example.ashkan.actionexample'

Can you help please?

**Comment by chalup** [comment]
@AshkanImmortal does this problem still occur? If so, what are the exact reproduction steps?

**Comment by chalup** [comment]
No response, so I'm closing this issue. @AshkanImmortal please reopen with more info if the problem still occurs.

**Comment by kifki** [comment]
Hello, I'm having the same issue.
Doesn't work with  `compile 'com.getbase:floatingactionbutton:1.9.0'` , but does with  `compile 'com.getbase:floatingactionbutton:1.8.0'`

**Comment by chalup** [comment]
@kifki gist your build.gradle, maybe it's some kind of dependencies conflict.

**Comment by kifki** [comment]
I tried to compile with v1.9.0, and it's working now. Sorry to have bothered you.
