### ISSUE TITLE
Make labels clickable

### ISSUE THREAD

**Issue by lynfogeek** [futuresimple/android-floating-action-button#95]
After showing my app to an handful of tester, I realized that most of them wanted to click on the label itself instead of the FloatingActionButton attached to it. 

It would be nice to handle it with the FloatingActionButton click/touch listener.

**Comment by chalup** [comment]
Great idea, but it's not there simple to implement it in a correct way. You
also need to extend the click able area vertically to match the FAB height,
make sure the margin between FAB and label is clickable too, show feedback
on FAB when label is touched, etc.

Having said that, this improvement is quite high on my TODO list for this
project.

**Comment by LewisRhine** [comment]
Have the fab and the label view inside a layout set to wrap content. Then have on click calls go to the layout inside of the label?

**Comment by tamiof** [comment]
The workaround I used was go to setTitle method inside FloatingActionButton and add:

label.setOnClickListener(new OnClickListener()
 {
                       @Override
			public void onClick(View v) 
			{
				FloatingActionButton.this.performClick();
			}
		});

Hopes this helps someone.

**Comment by AlexPari** [comment]
@tamiof your solution not worked for me, the performClick() returns to onClickListener of the FloatingActionMenu and not my FloatingActionButton...

**Comment by wjwarren** [comment]
@tamiof I found that making the label clickable involved slightly more than your suggestion above. See my commit https://github.com/wjwarren/android-floating-action-button/commit/10cdcb6ffa6e106a58f8d833ee010a9b97a3f2bf

**Comment by AndroidDeveloperLB** [comment]
I think it's better to use "setOnClickListener" on the label TextView and call "performClick" inside of it, on the "FloatingActionButton" itself. All of this, just when you create the labels TextViews.
It's much shorter this way.

Here's the relevant part (in "FloatingActionsMenu") :

    private void createLabels() {
            ...
            label.setOnClickListener(new OnClickListener() {
                @Override
                public void onClick(final View v) {
                    button.performClick();
                }
            });
            ...
        }
    }

**Comment by lynfogeek** [comment]
Maybe extend the touchable area of the FAB with a [TouchDelegate](http://developer.android.com/reference/android/view/TouchDelegate.html) would be more reliable than the `performClick()` solution.

If @chalup agrees with this solution I can make a PR next weekend

**Comment by AndroidDeveloperLB** [comment]
@lynfogeek Well, I offered to make it fully customizable, so that you could put whatever views you wish, and choose what to do on each clicking of which. This way, there won't be any weird workarounds for this case.

**Comment by lynfogeek** [comment]
@AndroidDeveloperLB but you **should not** have a use case where clicking on the label does something else than clicking on the FAB.

Helping such behavior via the library is bad design IMO.

**Comment by AndroidDeveloperLB** [comment]
@lynfogeek I didn't say it should or should not. I want to give the control to whoever uses it. This way, the developer that puts the views can also decide how to put them, with which animations, angle, and so on... if he does something weird with the functionality, it's his fault.

**Comment by danielesegato** [comment]
Which is the state of this issue?
Is someone working on it?

**Comment by AndroidDeveloperLB** [comment]
@danielesegato I don't know, but I've offered a very tiny change that you can do to make it work:
https://github.com/futuresimple/android-floating-action-button/issues/95#issuecomment-72355754

**Comment by devishankar** [comment]
By making the
private TextView getLabelView() {
        return (TextView) getTag(R.id.fab_label);
    } 

to public in FloatingActionButton.java and using this with floating action button will solve this problem
