### ISSUE TITLE
background color of floating action menu button

### ISSUE THREAD

**Issue by hirak141995** [futuresimple/android-floating-action-button#98]
Cant we change the color of floating action button programmatically?

fab:fab_addButtonColorNormal="@color/color"

This is what we do in xml. But how to change that programmatically?

**Comment by chalup** [comment]
This will be implemented as a part of #49

**Comment by viswakarmalovekush** [comment]
use this 
[ fab:menu_colorNormal="@color/orange"
        fab:menu_colorPressed="@color/orange_light"
        fab:menu_colorRipple="@color/white"](url)
